name: Build & Pack
env:
  PACKAGE_ID: ProtoEval
on:
  workflow_dispatch:
  push:
    branches: [ "main"]
    tags:
      - '*'
  pull_request:
    branches: [ "main" ]
permissions:
  packages: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v4
    
    - name: Prepare Tools
      uses: goreleaser/goreleaser-action@v3
      with:
        distribution: goreleaser
        version: latest
        args: -f .goreleaser.yaml --snapshot --clean #--debug
        workdir: cli
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: GoRelease After Hook
      run: ./hook.sh
      shell: bash
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Pack Nuget Package
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        arrTag=(${GITHUB_REF//\// })
        VERSION="${arrTag[2]}"
        echo Version: $VERSION
        VERSION="${VERSION//v}"
        echo Clean Version: $VERSION
        dotnet pack -v normal -c Release -p:PackageVersion=$VERSION -p:PackageId=$PACKAGE_ID -o nupkg ProtoEval/ProtoEval.csproj
    - name: Publish NuGet packages
      if: startsWith(github.ref, 'refs/tags/')
      run : dotnet nuget push nupkg/*.nupkg --api-key ${{ secrets.NUGET_ACCESS_TOKEN }} --source https://api.nuget.org/v3/index.json